### ISSUE TITLE
[MAP] Utopia Atmos.

### ISSUE THREAD

**Issue by kyrahabattoir** [mattroks101/InterBay#119]
I've done a few tests and we still have a few issues on utopia:

There are observations based on how air alarms work:
* All air alarms in an area share the same "mode" on the UI but not internally (bug).
* Air alarms will control all vents inside their area that share their frequency.

Multiple air alarms in the same area should be put on separate frequencies and matched to vents and scrubbers that are in the same physical location, there is no point having an alarm trigger and engaging vents that are separated from it by a door for instance.

For instance there is an air alarm in the fuel supply monitoring room that is part of the engine room area but doesn't actually have vents in the room it is in.

**Comment by OrangeMann** [comment]
That room has air alarm just to indicate if there is an air because otherwise air alarm in engine itself can't tell if there is any, if there is not, air alarm will work in entire area.
I was putting multiple air alarms in places such as corridors through potentially separtated rooms in it, like if there is alarm and firedoors will close in entire area.

What i mean is, i did that thinking multiple air alarm in same area actually sync their settings across them all in same area, meaning they would not cause any shitty stuff in it.

Manually changing frequency to all those issues on the map is not worth doing it. In fact, bay doesn't do that as well, so i don't think this is map-wise issue at the first place, @mattroks101.

**Comment by kyrahabattoir** [comment]
I'm just trying to find a solution to the frustration of trying to bring oxygen up in room A while room B is being overpressured at the same time because they are in the same area.

It's a bit frustrating sometimes.

**Comment by OrangeMann** [comment]
Well it's pretty hard to think of something useful but in the same time comfortable to use in this case.
